### ISSUE TITLE
Criar o board de atividades usando o Projects do github

### ISSUE THREAD

**Issue by Manuel-Antunes** [duardoqueiroz/Street-Fight-Arapiraca-Editon#14]
Nesse repositório, deve ser criado um project (no template Kamban with code reviews)
anexar as issues e sempre atualizar ele para ter uma melhor vizualização
além disso, SEMPRE ANEXEM AS ISSUES AOS DONOS

**Comment by guilherme-gjv** [comment]
Done! posso fechar?
